web/router.ex
defmodule ShoppingSite.Router do
  use ShoppingSite.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug ShoppingSite.Auth, repo: ShoppingSite.Repo
    plug ShoppingSite.CartPlug
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ShoppingSite do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/products", ProductController, only: [:index, :show] do
      get "/add_to_cart", ProductController, :add_to_cart, as: :add_to_cart
    end

    resources "/carts", CartController, only: [:index] do
      get "/check_out", CartController, :check_out, as: :check_out
      delete "/clean", CartController, :clean, as: :clean
    end

    resources "/orders", OrderController, param: "token" do
      get "/pay_with_credit_card", OrderController, :pay_with_credit_card, as: :pay_with_credit_card
    end

    resources "/items", CartItemController, only: [:delete, :update]
  end

  scope "/admin", ShoppingSite.Admin, as: :admin do
    pipe_through :browser

    resources "/products", ProductController
    resources "/users", UserController

    resources "/orders", OrderController do
      post "/cancel", OrderController, :cancel
      post "/ship", OrderController, :ship
      post "/shipped", OrderController, :shipped
      post "/return", OrderController, :return
    end

    get "/change_authority/:id",  UserController, :change_authority
    get "/products_list_view", ProductController, :list_view
  end

  scope "/account", ShoppingSite.Account, as: :account do
    pipe_through :browser

    resources "/orders", OrderController
  end
  # Other scopes may use custom stacks.
  # scope "/api", ShoppingSite do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule ShoppingSite.LayoutView do
  use ShoppingSite.Web, :view

  require Logger
  import ShoppingSite.CartController, only: [current_cart: 1]

  def cart_item_count(conn) do
    ShoppingSite.Repo.preload(current_cart(conn), :cart_items).cart_items
      |> length
  end

end

web/templates/layout/admin.html.eex
<%# <h1>Admin part!!!!</h1> %>

<%= link "products" , to: admin_product_path(@conn, :index), class: "btn btn-primary" %>

<%= link "users" , to: admin_user_path(@conn, :index), class: "btn btn-primary" %>

<%= link "Orders", to: admin_order_path(@conn, :index), class: "btn btn-primary" %>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello ShoppingSite!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container-fluid">
      <%= render "navbar.html", conn: @conn%>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <p class="alert alert-warning" role="alert"><%= get_flash(@conn, :warning) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>
    </div>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/layout/navbar.html.eex
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Shopping Site</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
          <%= link "Product" , to: product_path(@conn, :index)%>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="">
          <%= link to: cart_path(@conn, :index) do %>
            Cart (<%= cart_item_count(@conn) %>)
          <% end %>
        </li>
        <%= if !@conn.assigns.current_user do %>
          <li><%= link "Log In" , to: session_path(@conn, :new) %></li>
          <li><%= link "Register" , to: user_path(@conn, :new) %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Hi!, <%= @conn.assigns.current_user.username %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link "Log out", to: session_path(@conn, :delete, @conn.assigns.current_user), method: :delete %></li>
              <li><%= link "Product Management", to: admin_product_path(@conn, :index) %></li>
              <li><%= link "Orders", to: account_order_path(@conn, :index) %></li>
            </ul>
          </li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>