web/router.ex
defmodule ShoppingSite.Router do
  use ShoppingSite.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug ShoppingSite.Auth, repo: ShoppingSite.Repo
    plug ShoppingSite.CartPlug
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ShoppingSite do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/products", ProductController, only: [:index, :show] do
      get "/add_to_cart", ProductController, :add_to_cart, as: :add_to_cart
    end

    resources "/carts", CartController, only: [:index] do
      get "/check_out", CartController, :check_out, as: :check_out
      delete "/clean", CartController, :clean, as: :clean
    end

    resources "/orders", OrderController, param: "token" do
      get "/pay_with_credit_card", OrderController, :pay_with_credit_card, as: :pay_with_credit_card
    end

    resources "/items", CartItemController, only: [:delete, :update]
  end

  scope "/admin", ShoppingSite.Admin, as: :admin do
    pipe_through :browser

    resources "/products", ProductController
    resources "/users", UserController

    resources "/orders", OrderController do
      post "/cancel", OrderController, :cancel
      post "/ship", OrderController, :ship
      post "/shipped", OrderController, :shipped
      post "/return", OrderController, :return
    end

    get "/change_authority/:id",  UserController, :change_authority
    get "/products_list_view", ProductController, :list_view
  end

  scope "/account", ShoppingSite.Account, as: :account do
    pipe_through :browser

    resources "/orders", OrderController
  end
  # Other scopes may use custom stacks.
  # scope "/api", ShoppingSite do
  #   pipe_through :api
  # end
end

web/models/cart.ex
defmodule ShoppingSite.Cart do
  use ShoppingSite.Web, :model

  alias ShoppingSite.Repo

  schema "carts" do

    has_many :cart_items, ShoppingSite.CartItem, on_delete: :delete_all
    has_many :products, through: [:cart_items, :product]

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [])
    |> validate_required([])
  end

  @doc """
  debug session
  alias ShoppingSite.Repo
  alias ShoppingSite.Cart
  cart = Repo.get Cart, 33
  products_in_cart = Repo.all Ecto.assoc(cart, :products)
  products_in_cart |> Enum.any?(& &1.id == 16)
  """
  def clean_cart_items(cart) do
    Repo.preload(cart, :cart_items).cart_items
      |> Enum.map(& Repo.delete(&1))
  end

end

web/controllers/cart_controller.ex
defmodule ShoppingSite.CartController do
  use ShoppingSite.Web, :controller

  require Logger

  alias ShoppingSite.Repo
  alias ShoppingSite.Order
  alias ShoppingSite.Cart
  alias ShoppingSite.OrderInfo

  import ShoppingSite.UserController, only: [authenticate: 2]
  plug :authenticate when action in [:check_out]

  def index(conn, _params) do
    # cart_items =
    #   Repo.preload(current_cart(conn), :cart_items).cart_items

    products =
      Repo.preload(current_cart(conn), :products).products

    render conn, "index.html", products: products
  end

  def check_out(conn, _params) do
    order_info_changeset = OrderInfo.changeset(%OrderInfo{})
    order_changeset = Order.changeset(%Order{info: order_info_changeset})
    render conn, "check_out.html", order_changeset: order_changeset
  end

  def clean(conn, _params) do
    # Repo.preload(current_cart(conn), :cart_items).cart_items
    #   |> Enum.map(& Repo.delete(&1))
    Cart.clean_cart_items(current_cart(conn))

    conn
      |> put_flash(:info, "Cart cleaned")
      |> redirect(to: cart_path(conn, :index))
  end

  def current_cart(conn) do
    conn.assigns.current_cart
  end

end

web/views/cart_view.ex
defmodule ShoppingSite.CartView do
  use ShoppingSite.Web, :view

  alias ShoppingSite.Repo
  import ShoppingSite.CartController, only: [current_cart: 1]

  def cart_total_price(conn) do

    Repo.preload(current_cart(conn), :cart_items).cart_items
      |> Repo.preload(:product)
      |> Enum.reduce(0, fn x, acc ->
            (x.product.price*x.quantity) + acc end)
  end

  def present?(photo) do
    photo.file_name != ""
  end

  def get_cart_id(conn) do
    Plug.Conn.get_session(conn, :cart_id)
  end

  def get_cart_items(conn) do
    products =
      Repo.preload(current_cart(conn), :products).products
  end

  def get_cart_item(conn, product) do
      Repo.preload(current_cart(conn), :cart_items).cart_items
        |> Enum.find(fn x -> x.product_id == product.id end)
  end

  def get_changeset(conn, product) do
    Repo.preload(current_cart(conn), :cart_items).cart_items
      |> Enum.find(fn x -> x.product_id == product.id end)
      |> ShoppingSite.CartItem.changeset(%{})
  end

  def get_selections(conn, product) do
    cart_item =
      Repo.preload(current_cart(conn), :cart_items).cart_items
        |> Enum.find(fn x -> x.product_id == product.id end)

    1..cart_item.quantity |> Enum.to_list
  end

end

web/templates/cart/check_out.html.eex
<div class="row">
  <div class="col-md-12">
    <h2> Order information </h2>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th width="80%">product information</th>
          <th>price</th>
        </tr>
      </thead>
      <tbody>
        <%= for product <- get_cart_items(@conn) do %>
         之後要顯示數量所以要用 cart_item 做
          <tr>
            <td>
              <%= link to: product_path(@conn, :show, product.id) do %>
                <%= product.title %>
              <% end %>
            </td>
            <td>
              <%= product.price %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <div class="total clearfix">
      <span class="pull-right">
        total <%= cart_total_price(@conn) %>
      </span>
    </div>

    <h2> Order information </h2>

    <div class="order-form">
      <%= render "order_form.html", changeset: @order_changeset, action: order_path(@conn, :create) %>
    </div>

  </div>
</div>

web/templates/cart/index.html.eex
<div class="row">

  <%= link "Clean Cart",
      to: cart_clean_path(@conn, :clean, current_cart(@conn)),
      class: "pull-right",
      style: "text-decoration: underline;",
      method: :delete, data: [confirm: "Are you sure?"] %>

  <div class="col-md-12">
    <h2>Cart</h2>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th colspan="2">Product information</th>
          <th>price</th>
          <th>quantity</th>
          <th>operation</th>
        </tr>
      </thead>

      <tbody>
        <%= for product <- @products do %>
          <tr>
            <td>
              <%= link to: product_path(@conn, :show, product.id) do %>
                <%= if present?(product.photo) do %>
                  <img class="thumbnail" src="<%= ShoppingSite.PhotoUploader.url({product.photo, product}, :thumb) %>"/>
                <% else %>
                  <img class="thumbnail" src="http://placehold.it/200x200&text=No Pic"/>
                <% end %>
              <% end %>
            </td>
            <td>
              <%= link to: product_path(@conn, :show, product.id) do %>
                <%= product.title %>
              <% end %>
            </td>
            <td>
              <%= product.price %>
            </td>
            <td>

              <%= form_for get_changeset(@conn, product),
                  cart_item_path(@conn, :update, get_cart_item(@conn, product)), fn f -> %>
                <%= label f, :quantity, "Quantity",
                    class: "control-label" %>
                <%= select f, :quantity, get_selections(@conn, product),
                    class: "form-control", prompt: "Choose quantity" %>
                <%= submit "Submit", class: "btn btn-primary pull-right" %>
              <% end %>
            </td>
            <td>
              <%= link "delete",
                  to: cart_item_path(@conn, :delete, product),
                  method: :delete, class: "btn btn-xs btn-danger" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <div class="total clearfix">
      <span class="pull-right">
        <span> total <%= cart_total_price(@conn) %> </span>
      </span>
    </div>

    <div class="checkout clearfix">
      <span class="pull-right">
        <%= link "Check out", to: cart_check_out_path(@conn, :check_out, get_cart_id(@conn)), class: "btn btn-lg btn-danger" %>
      </span>
    </div>
  </div>
</div>

web/templates/cart/order_form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops! something went wrong!</p>
    </div>
  <%= end %>

  <%= inputs_for f, :info, fn fp -> %>
    <div class="form-group">
      <%= label fp, :billing_name, class: "control-label" %>
      <%= text_input fp, :billing_name, class: "form-control" %>
      <%= error_tag fp, :billing_name %>
    </div>

    <div class="form-group">
      <%= label fp, :billing_address, class: "control-label" %>
      <%= text_input fp, :billing_address, class: "form-control" %>
      <%= error_tag fp, :billing_address %>
    </div>

    <div class="form-group">
      <%= label fp, :shipping_name, class: "control-label" %>
      <%= text_input fp, :shipping_name, class: "form-control" %>
      <%= error_tag fp, :shipping_name %>
    </div>

    <div class="form-group">
      <%= label fp, :shipping_address, class: "control-label" %>
      <%= text_input fp, :shipping_address, class: "form-control" %>
      <%= error_tag fp, :shipping_address %>
    </div>
  <% end %>

  <div class="form-group">
    <%= submit "Check out", class: "btn btn-lg btn-danger pull-right" %>
  </div>

<% end %>